/**
 * @typedef {{tag: string, component: function}} registry
 *
 * @description
 * Mapping of tag names to component functions.
 * The tag names can be capitalized (like React),
 * single words (like html), or hyphenated (like web-components).
 *
 * The component functions should be functions that return {Node}
 * objects (generated from html tagged template functions).
 *
 * @example
 * import CustomHeader from './CustomHeader'
 * import CustomLogin from './CustomLogin'
 *
 *
 * const { registerHtml } = Tram()
 * const html = registerHtml({
 *   CustomHeader,
 *   'custom-login': CustomLogin,
 * })
 *
 *
 * const page = () => {
 *   return html`
 *     <div>
 *       <CustomHeader />
 *       <custom-login />
 *     </div>
 *   `
 * }
 */

/**
 * @typedef {Function} component
 *
 * @param {Object} [props] Attributes, properties, and event handlers.
 * These can be custom properties, or ones found in standard html components.
 *
 * @param {Node[]} [children] Components inside the start and close tag.
 * Tags by default can be self-closing, so you may have no children passed in.
 *
 * @returns {Node}
 *
 * @description
 * Function component that returns some Node. It has the same interface as standard DOM
 * in that it takes in props and children. They are written by users of the Tram-One Framework.
 *
 * @example <caption>FancyList.js</caption>
 * const { registerHtml } = Tram()
 * const html = registerHtml()
 *
 *
 * export default (props, children) => {
 *   const listStyle = `color: ${props.color}; font-size: 2em; border: black solid 2px;`
 *   const listClasses = `fancy-list ${props.className}`
 *   const onSelect = props.onclick
 *   return html`
 *     <ul class=${listClasses} style=${listSTyle} onclick=${onSelect}>
 *       ${children}
 *     </ul>
 *   `
 * }
 *
 * @example <caption>ShoppingList.js</caption>
 * import FancyList from './FancyList'
 * const { registerHtml } = Tram()
 * const html = registerHtml({
 *   'fancy-list': FancyList
 * })
 *
 * export default () => {
 *   const onSelectFancyList = (event) => {
 *     console.log(event)
 *   }
 *   return html`
 *     <fancy-list class="shopping-lsit" onclick=${onSelectFancyList} color="blue">
 *       <li>pasta</li>
 *       <li>milk</li>
 *       <li>juice</li>
 *     </fancy-list>
 *   `
 * }
 */

/**
 * @typedef {Function} html
 *
 * @description
 * Function generated by `registerDom`, `registerHtml`, and `registerSvg`.
 * It takes in an XML template and returns a DOM Tree.
 * If a registry object was passed in when building the function, then tags that
 * are in the registry will be called and used.
 *
 * @param {String} template XML Template with standard and custom components
 *
 * @returns {Node} DOM Tree from XML Template
 *
 * @example
 * const { registerHtml } = Tram()
 * const html = registerHtml()
 *
 *
 * const header = () => html`<h1>Learn about Tram-One!</h1>`
 */
