extends: standard
plugins:
  - standard
  - promise
env:
  node: true
rules:
  block-scoped-var: 2
  class-methods-use-this: 2
  consistent-return: 2
  curly: 2
  eqeqeq: 2
  no-alert: 2
  no-else-return: 2
  no-implicit-coercion: 2
  no-multi-str: 2
  no-new: 2
  no-return-assign: 2
  wrap-iife: 2
  yoda: 2
  brace-style: 2
  indent:
    - 2
    - 2
    - SwitchCase: 1
  space-before-function-paren:
    - 2
    - never
  keyword-spacing: 2
  key-spacing: 2
  no-trailing-spaces: 2
  quotes:
    - 2
    - single
    - avoid-escape
  space-infix-ops: 2
  spaced-comment: 2
  arrow-spacing: 2
  no-var: 2
  prefer-template: 2

  prefer-const: 1
  prefer-spread: 1
  no-useless-call: 1
  sort-imports: 1
