/* eslint valid-jsdoc: 2 */

/* types */

/**
 * @typedef {object} tramSpace
 *
 * @description
 *
 * <blockquote>
 *   This object is an interface you should adhere to,
 *   not a value that is constructed or generated by a function.
 * </blockquote>
 *
 * Object where Tram-One will store internal state and listeners.
 * It is not recommended that you interact with this object directly.
 * When testing or running on non-browser environments you can provide your own mock `tramSpace`.
 *
 * @example
 * global.tramSpace = {}
 * import { registerHtml, start } from 'tram-one'
 *
 */

/* modules */

/**
 * @module Tram-One
 *
 * @description
 * This module exposes several functions which (by default) attach state on the window object.
 * If you want to attach state objects and listeners on a different object, define a {@link tramSpace | global space object} beforehand.
 *
 * @example
 * import { registerHtml, start } from 'tram-one'
 */
